services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
      - db_data:/app/db
    working_dir: /app
    command: sh -c "node seed.js && node index.js"

  client:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - DOCKER=true
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    depends_on:
      - server

volumes:
  db_data:
